import = ["/home/dbaoty/.config/alacritty/rose-pine.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 375

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window.padding]
x = 12
y = 12
