#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale --no-fehbg $HOME/porn/wallpapers/wallhaven-l8q5mq.jpg &
pgrep -x polybar > /dev/null || polybar bar &
pgrep -x picom > /dev/null || picom --config $HOME/.config/picom/picom.conf &
xrdb ~/.Xresources &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	1
bspc config window_gap          	12
bspc config top_padding						28

bspc config focus_follows_pointer	true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
